// Mocks generated by Mockito 5.4.6 from annotations
// in cards/test/sqlite_card_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cards/helpers/i_database_helper.dart' as _i2;
import 'package:cards/models/card_item.dart' as _i4;
import 'package:cards/services/error_handling_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatabaseHelper extends _i1.Mock implements _i2.IDatabaseHelper {
  MockIDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertCard(_i4.CardItem? card) =>
      (super.noSuchMethod(
            Invocation.method(#insertCard, [card]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.CardItem>> getCards() =>
      (super.noSuchMethod(
            Invocation.method(#getCards, []),
            returnValue: _i3.Future<List<_i4.CardItem>>.value(<_i4.CardItem>[]),
          )
          as _i3.Future<List<_i4.CardItem>>);

  @override
  _i3.Future<int> getNextSortOrder() =>
      (super.noSuchMethod(
            Invocation.method(#getNextSortOrder, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> updateCardSortOrders(List<_i4.CardItem>? cards) =>
      (super.noSuchMethod(
            Invocation.method(#updateCardSortOrders, [cards]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> deleteCard(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCard, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> updateCard(_i4.CardItem? card) =>
      (super.noSuchMethod(
            Invocation.method(#updateCard, [card]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> deleteAllCards() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllCards, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.CardItem?> getCard(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCard, [id]),
            returnValue: _i3.Future<_i4.CardItem?>.value(),
          )
          as _i3.Future<_i4.CardItem?>);

  @override
  _i3.Future<int> backfillLogoPathsFromTitles({bool? dryRun = true}) =>
      (super.noSuchMethod(
            Invocation.method(#backfillLogoPathsFromTitles, [], {
              #dryRun: dryRun,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [ErrorHandlingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorHandlingService extends _i1.Mock
    implements _i5.ErrorHandlingService {
  MockErrorHandlingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void handleError(
    dynamic error,
    StackTrace? stackTrace, {
    String? context,
    Map<String, dynamic>? additionalData,
    bool? isFatal = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #handleError,
      [error, stackTrace],
      {#context: context, #additionalData: additionalData, #isFatal: isFatal},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void handleLogoCacheError(dynamic error, {String? operation}) =>
      super.noSuchMethod(
        Invocation.method(
          #handleLogoCacheError,
          [error],
          {#operation: operation},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleNavigationError(dynamic error, {String? route}) =>
      super.noSuchMethod(
        Invocation.method(#handleNavigationError, [error], {#route: route}),
        returnValueForMissingStub: null,
      );

  @override
  void handleDatabaseError(dynamic error, {String? query}) =>
      super.noSuchMethod(
        Invocation.method(#handleDatabaseError, [error], {#query: query}),
        returnValueForMissingStub: null,
      );

  @override
  String getUserFriendlyMessage(dynamic error) =>
      (super.noSuchMethod(
            Invocation.method(#getUserFriendlyMessage, [error]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getUserFriendlyMessage, [error]),
            ),
          )
          as String);

  @override
  Map<String, dynamic> getErrorStats() =>
      (super.noSuchMethod(
            Invocation.method(#getErrorStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void clearHistory() => super.noSuchMethod(
    Invocation.method(#clearHistory, []),
    returnValueForMissingStub: null,
  );
}
