#!/bin/bash

# Simple Manual Testing - Download Test Codes
# This script helps you download real test QR codes and barcodes from online generators

echo "🎯 Manual Testing - Quick Setup"
echo "================================"
echo ""
echo "Option 1: Generate QR Codes Online (No Installation Needed) ✅"
echo "-----------------------------------------------------------"
echo ""
echo "Step 1: Generate QR Codes"
echo "  Visit: https://www.qr-code-generator.com/"
echo ""
echo "  Generate these codes (save each as PNG):"
echo "    QR Code 1: TEXT = 'TEST_QR_SCAN_001'"
echo "    QR Code 2: TEXT = 'TEST_QR_GITHUB_LINK'"
echo "    QR Code 3: TEXT = 'https://github.com/pietergeerts/cards'"
echo ""
echo "  → Download 3 QR code images as:"
echo "    - test_qr_001.png"
echo "    - test_qr_002.png"
echo "    - test_qr_github.png"
echo ""

echo "Step 2: Generate Barcodes"
echo "  Visit: https://barcode.tec-it.com/barcodegenerator.aspx"
echo ""
echo "  Generate these barcodes (save each as PNG):"
echo "    Barcode 1: FORMAT = EAN-13, VALUE = '5901234123457'"
echo "    Barcode 2: FORMAT = Code128, VALUE = 'TEST123CODE'"
echo ""
echo "  → Download 2 barcode images as:"
echo "    - test_barcode_ean13.png"
echo "    - test_barcode_code128.png"
echo ""

echo "Step 3: Organize Test Files"
echo "  Create directory: ~/card_test_codes"
echo "  Move all 5 images there"
echo ""
echo "    mkdir -p ~/card_test_codes"
echo "    mv ~/Downloads/test_*.png ~/card_test_codes/"
echo ""

echo "=================="
echo "Option 2: Using Pre-Built Codes"
echo "------------------ "
echo ""
echo "If you don't want to generate codes, use EXISTING QR codes:"
echo ""
echo "📱 Real-World QR Codes to Test:"
echo "  - Scan GitHub repo QR: https://qr.github.com/?url=https://github.com"
echo "  - Scan WiFi QR from your router"
echo "  - Scan ISBN barcode from any book"
echo "  - Scan product barcode from packaging"
echo ""

echo ""
echo "=================="
echo "Step 4: Push to Emulator"
echo "=================="
echo ""
echo "Option A: From Terminal"
echo ""
echo "  # Create Pictures directory if doesn't exist"
echo "  adb shell mkdir -p /sdcard/Pictures"
echo ""
echo "  # Push individual files"
echo "  for file in ~/card_test_codes/*.png; do"
echo "    filename=\$(basename \$file)"
echo "    adb push \$file /sdcard/Pictures/\$filename"
echo "  done"
echo ""

echo "Option B: Using ADB directly"
echo ""
echo "  adb push ~/card_test_codes/test_qr_001.png /sdcard/Pictures/"
echo "  adb push ~/card_test_codes/test_qr_002.png /sdcard/Pictures/"
echo "  adb push ~/card_test_codes/test_qr_github.png /sdcard/Pictures/"
echo "  adb push ~/card_test_codes/test_barcode_ean13.png /sdcard/Pictures/"
echo "  adb push ~/card_test_codes/test_barcode_code128.png /sdcard/Pictures/"
echo ""

echo "Verify files were pushed:"
echo "  adb shell ls /sdcard/Pictures/"
echo ""

echo ""
echo "=================="
echo "Step 5: Run App & Test"
echo "=================="
echo ""
echo "  1. Start app: flutter run"
echo "  2. Tap 'Add Card' → 'Scan from Photo'"
echo "  3. Select test images from gallery"
echo "  4. Verify detection and form population"
echo ""

echo ""
echo "=================="
echo "Terminal Quick Commands"
echo "=================="  
echo ""
echo "# Verify emulator is running"
echo "adb devices"
echo ""
echo "# Create Pictures directory"
echo "adb shell mkdir -p /sdcard/Pictures"
echo ""
echo "# Push all test images at once"
echo "pushd ~/card_test_codes && for f in *.png; do adb push \"\$f\" /sdcard/Pictures/; done && popd"
echo ""
echo "# Verify uploaded"
echo "adb shell ls -la /sdcard/Pictures/"
echo ""
