name: cards
description: "Just Cards - Digital wallet for QR codes and barcodes."

# Prevent publishing to pub.dev
# publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.1.0+19

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.0.1
  sqflite: ^2.2.0
  path: ^1.8.3
  barcode_widget: ^2.0.4
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  fl_mlkit_scanning: ^5.2.2
  share_plus: ^7.2.1
  file_selector: ^1.0.3
  flutter_svg: ^2.1.0
  path_provider: ^2.0.0
  screen_brightness: ^1.0.1
  simple_icons: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
