// Mocks generated by Mockito 5.4.6 from annotations
// in cards/test/services/card_expiry_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cards/models/card_item.dart' as _i6;
import 'package:cards/repositories/card_repository_interface.dart' as _i2;
import 'package:cards/utils/result.dart' as _i5;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRepository extends _i1.Mock implements _i2.CardRepository {
  MockCardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> insertCard(_i6.CardItem? card) =>
      (super.noSuchMethod(
            Invocation.method(#insertCard, [card]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
                this,
                Invocation.method(#insertCard, [card]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.CardItem>>> getCards() =>
      (super.noSuchMethod(
            Invocation.method(#getCards, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.CardItem>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.CardItem>>>(
                    this,
                    Invocation.method(#getCards, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.CardItem>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> getNextSortOrder() =>
      (super.noSuchMethod(
            Invocation.method(#getNextSortOrder, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
                this,
                Invocation.method(#getNextSortOrder, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateCardSortOrders(
    List<_i6.CardItem>? cards,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCardSortOrders, [cards]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateCardSortOrders, [cards]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> deleteCard(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCard, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
                this,
                Invocation.method(#deleteCard, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> updateCard(_i6.CardItem? card) =>
      (super.noSuchMethod(
            Invocation.method(#updateCard, [card]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
                this,
                Invocation.method(#updateCard, [card]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteAllCards() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllCards, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deleteAllCards, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.CardItem?>> getCard(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCard, [id]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.CardItem?>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.CardItem?>>(
                    this,
                    Invocation.method(#getCard, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.CardItem?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> backfillLogoPathsFromTitles({
    bool? dryRun = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#backfillLogoPathsFromTitles, [], {
              #dryRun: dryRun,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
                this,
                Invocation.method(#backfillLogoPathsFromTitles, [], {
                  #dryRun: dryRun,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, int>>);
}
