# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"

      - name: Create key.properties
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Decode upload-keystore.jks
        run: |
          echo "${{ secrets.UPLOAD_KEYSTORE_BASE64 }}" | base64 -d > android/upload-keystore.jks

      - name: Install dependencies
        run: flutter pub get

      # - name: Format code
      #   run: flutter format --set-exit-if-changed .

      # - name: Analyze project source
      #   run: flutter analyze

      - name: Run tests
        run: flutter test


      # Build Android App Bundle (AAB) with symbols for Play Console
      - name: Build Android App Bundle (AAB) with symbols
        run: flutter build appbundle --obfuscate --split-debug-info=build/symbols --release

      # Archive the AAB and symbols for download
      - name: Upload AAB and symbols artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle-and-symbols
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/symbols/

      # Build release APK and save it as an artifact
      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
