name: Dependabot Auto-Merge

# Enable auto-merge for Dependabot pull requests when checks pass.
# This workflow listens for PR events (opened, reopened, synchronize, labeled)
# and enables GitHub native auto-merge for PRs created by Dependabot.
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch: {}

jobs:
  automerge:
    # Only run this job for Dependabot actors
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable GitHub auto-merge for this PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          # Use the default GITHUB_TOKEN provided to the runner
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
